export const SET_BT_MODULE = 'SET_BTMODULE';
export const ADD_DEVICE = 'ADD_DEVICE';
export const ADD_DEVICE_TO_LIST = 'ADD_DEVICE_TO_LIST';
export const SET_INFO = 'SET_INFO';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';
export const SET_BLUETOOTH_STATUS = 'SET_BLUETOOTH_STATUS';
export const SET_BT_SEARCHING = 'SET_BT_SEARCHING';
export const SET_TRAVELING = 'SET_TRAVELING';
export const SET_BUTTON_TEXT = 'SET_BUTTON_TEXT';
export const SET_BUTTON_ICON = 'SET_BUTTON_ICON';
export const SET_ENGINE_LOAD = 'SET_ENGINE_LOAD';
export const SET_ENGINE_LOAD_SELECTED = 'SET_ENGINE_LOAD_SELECTED';
export const SET_COOLANT_TEMPERATURE = 'SET_COOLANT_TEMPERATURE';
export const SET_COOLANT_TEMPERATURE_SELECTED =
  'SET_COOLANT_TEMPERATURE_SELECTED';
export const SET_FUEL_PRESSURE = 'SET_FUEL_PRESSURE';
export const SET_FUEL_PRESSURE_SELECTED = 'SET_FUEL_PRESSURE_SELECTED';
export const SET_INTAKE_MANIFOLD_PRESSURE = 'SET_INTAKE_MANIFOLD_PRESSURE';
export const SET_INTAKE_MANIFOLD_PRESSURE_SELECTED =
  'SET_INTAKE_MANIFOLD_PRESSURE_SELECTED';
export const SET_RPM = 'SET_RPM';
export const SET_RPM_SELECTED = 'SET_RPM_SELECTED';
export const SET_SPEED = 'SET_SPEED';
export const SET_SPEED_SELECTED = 'SET_SPEED_SELECTED';
export const SET_TIMING_ADVANCE = 'SET_TIMING_ADVANCE';
export const SET_TIMING_ADVANCE_SELECTED = 'SET_TIMING_ADVANCE_SELECTED';
export const SET_INTAKE_AIR_TEMPERATURE = 'SET_INTAKE_AIR_TEMPERATURE';
export const SET_INTAKE_AIR_TEMPERATURE_SELECTED =
  'SET_INTAKE_AIR_TEMPERATURE_SELECTED';
export const SET_AIR_FLOW_RATE = 'SET_AIR_FLOW_RATE';
export const SET_AIR_FLOW_RATE_SELECTED = 'SET_AIR_FLOW_RATE_SELECTED';
