export const SET_BT_MODULE = 'SET_BTMODULE';
export const ADD_DEVICE = 'ADD_DEVICE';
export const ADD_DEVICE_TO_LIST = 'ADD_DEVICE_TO_LIST';
export const ADD_TO_RESPONSE = 'ADD_TO_RESPONSE';
export const SET_INFO = 'SET_INFO';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';
export const SET_BLUETOOTH_STATUS = 'SET_BLUETOOTH_STATUS';
export const SET_UUID = 'SET_UUID';

export const SET_RPM = 'SET_RPM';
export const SET_RPM_SELECTED = 'SET_RPM_SELECTED';
export const SET_BT_SEARCHING = 'SET_BT_SEARCHING';
export const SET_TRAVELING = 'SET_TRAVELING';
export const SET_BUTTON_TEXT = 'SET_BUTTON_TEXT';
export const SET_BUTTON_ICON = 'SET_BUTTON_ICON';
