export const SET_BT_MODULE = 'SET_BTMODULE';
export const ADD_DEVICE = 'ADD_DEVICE';
export const ADD_DEVICE_TO_LIST = 'ADD_DEVICE_TO_LIST';
export const SET_INFO = 'SET_INFO';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';
export const SET_BLUETOOTH_STATUS = 'SET_BLUETOOTH_STATUS';
export const SET_BT_SEARCHING = 'SET_BT_SEARCHING';
export const SET_TRAVELING = 'SET_TRAVELING';
export const SET_BUTTON_TEXT = 'SET_BUTTON_TEXT';
export const SET_BUTTON_ICON = 'SET_BUTTON_ICON';

export const SET_TROUBLE_CODES_QUANTITY = 'SET_TROUBLE_CODES_QUANTITY';
export const SET_TROUBLE_CODES = 'SET_TROUBLE_CODES';

export const SET_ENGINE_LOAD = 'SET_ENGINE_LOAD';
export const SET_ENGINE_LOAD_SELECTED = 'SET_ENGINE_LOAD_SELECTED';
export const SET_COOLANT_TEMPERATURE = 'SET_COOLANT_TEMPERATURE';
export const SET_COOLANT_TEMPERATURE_SELECTED =
  'SET_COOLANT_TEMPERATURE_SELECTED';
export const SET_FUEL_PRESSURE = 'SET_FUEL_PRESSURE';
export const SET_FUEL_PRESSURE_SELECTED = 'SET_FUEL_PRESSURE_SELECTED';
export const SET_INTAKE_MANIFOLD_PRESSURE = 'SET_INTAKE_MANIFOLD_PRESSURE';
export const SET_INTAKE_MANIFOLD_PRESSURE_SELECTED =
  'SET_INTAKE_MANIFOLD_PRESSURE_SELECTED';
export const SET_RPM = 'SET_RPM';
export const SET_RPM_SELECTED = 'SET_RPM_SELECTED';
export const SET_SPEED = 'SET_SPEED';
export const SET_SPEED_SELECTED = 'SET_SPEED_SELECTED';
export const SET_TIMING_ADVANCE = 'SET_TIMING_ADVANCE';
export const SET_TIMING_ADVANCE_SELECTED = 'SET_TIMING_ADVANCE_SELECTED';
export const SET_INTAKE_AIR_TEMPERATURE = 'SET_INTAKE_AIR_TEMPERATURE';
export const SET_INTAKE_AIR_TEMPERATURE_SELECTED =
  'SET_INTAKE_AIR_TEMPERATURE_SELECTED';
export const SET_AIR_FLOW_RATE = 'SET_AIR_FLOW_RATE';
export const SET_AIR_FLOW_RATE_SELECTED = 'SET_AIR_FLOW_RATE_SELECTED';
export const SET_THROTTLE_POSITION = 'SET_THROTTLE_POSITION';
export const SET_THROTTLE_POSITION_SELECTED = 'SET_THROTTLE_POSITION_SELECTED';
export const SET_RUN_TIME_SINCE_ENGINE_START =
  'SET_RUN_TIME_SINCE_ENGINE_START';
export const SET_RUN_TIME_SINCE_ENGINE_START_SELECTED =
  'SET_RUN_TIME_SINCE_ENGINE_START_SELECTED';
export const SET_DISTANCE_TRAVELED_WITH_MIL_ON =
  'SET_DISTANCE_TRAVELED_WITH_MIL_ON';
export const SET_DISTANCE_TRAVELED_WITH_MIL_ON_SELECTED =
  'SET_DISTANCE_TRAVELED_WITH_MIL_ON_SELECTED';
export const SET_FUEL_RAIL_PRESSURE = 'SET_FUEL_RAIL_PRESSURE';
export const SET_FUEL_RAIL_PRESSURE_SELECTED =
  'SET_FUEL_RAIL_PRESSURE_SELECTED';
export const SET_FUEL_RAIL_GAUGE = 'SET_FUEL_RAIL_GAUGE';
export const SET_FUEL_RAIL_GAUGE_SELECTED = 'SET_FUEL_RAIL_GAUGE_SELECTED';
export const SET_COMMANDED_EGR = 'SET_COMMANDED_EGR';
export const SET_COMMANDED_EGR_SELECTED = 'SET_COMMANDED_EGR_SELECTED';
export const SET_EGR_ERROR = 'SET_EGR_ERROR';
export const SET_EGR_ERROR_SELECTED = 'SET_EGR_ERROR_SELECTED';
export const SET_FUEL_LEVEL = 'SET_FUEL_LEVEL';
export const SET_FUEL_LEVEL_SELECTED = 'SET_FUEL_LEVEL_SELECTED';
export const SET_WARM_UPS_SINCE_CODES_CLEARED =
  'SET_WARM_UPS_SINCE_CODES_CLEARED';
export const SET_WARM_UPS_SINCE_CODES_CLEARED_SELECTED =
  'SET_WARM_UPS_SINCE_CODES_CLEARED_SELECTED';
export const SET_DISTANCE_TRAVELED_SINCE_CODES_CLEARED =
  'SET_DISTANCE_TRAVELED_SINCE_CODES_CLEARED';
export const SET_DISTANCE_TRAVELED_SINCE_CODES_CLEARED_SELECTED =
  'SET_DISTANCE_TRAVELED_SINCE_CODES_CLEARED_SELECTED';
export const SET_CONTROL_MODULE_VOLTAGE = 'SET_CONTROL_MODULE_VOLTAGE';
export const SET_CONTROL_MODULE_VOLTAGE_SELECTED =
  'SET_CONTROL_MODULE_VOLTAGE_SELECTED';
export const SET_FUEL_AIR_COMMANDED_EQUIVALENCE_RATIO =
  'SET_FUEL_AIR_COMMANDED_EQUIVALENCE_RATIO';
export const SET_FUEL_AIR_COMMANDED_EQUIVALENCE_RATIO_SELECTED =
  'SET_FUEL_AIR_COMMANDED_EQUIVALENCE_RATIO_SELECTED';
export const SET_RELATIVE_THROTTLE_POSITION = 'SET_RELATIVE_THROTTLE_POSITION';
export const SET_RELATIVE_THROTTLE_POSITION_SELECTED =
  'SET_RELATIVE_THROTTLE_POSITION_SELECTED';
export const SET_AMBIENT_AIR_TEMPERATURE = 'SET_AMBIENT_AIR_TEMPERATURE';
export const SET_AMBIENT_AIR_TEMPERATURE_SELECTED =
  'SET_AMBIENT_AIR_TEMPERATURE_SELECTED';
export const SET_TIME_RUN_WITH_MIL_ON = 'SET_TIME_RUN_WITH_MIL_ON';
export const SET_TIME_RUN_WITH_MIL_ON_SELECTED =
  'SET_TIME_RUN_WITH_MIL_ON_SELECTED';
export const SET_TIME_SINCE_TROUBLE_CODES_CLEARED =
  'SET_TIME_SINCE_TROUBLE_CODES_CLEARED';
export const SET_TIME_SINCE_TROUBLE_CODES_CLEARED_SELECTED =
  'SET_TIME_SINCE_TROUBLE_CODES_CLEARED_SELECTED';
export const SET_FUEL_TYPE = 'SET_FUEL_TYPE';
export const SET_FUEL_TYPE_SELECTED = 'SET_FUEL_TYPE_SELECTED';
export const SET_FUEL_RAIL_ABSOLUTE_PRESSURE =
  'SET_FUEL_RAIL_ABSOLUTE_PRESSURE';
export const SET_FUEL_RAIL_ABSOLUTE_PRESSURE_SELECTED =
  'SET_FUEL_RAIL_ABSOLUTE_PRESSURE_SELECTED';
export const SET_RELATIVE_ACCELERATOR_PEDAL_POSITION =
  'SET_RELATIVE_ACCELERATOR_PEDAL_POSITION';
export const SET_RELATIVE_ACCELERATOR_PEDAL_POSITION_SELECTED =
  'SET_RELATIVE_ACCELERATOR_PEDAL_POSITION_SELECTED';
export const SET_ENGINE_OIL_TEMPERATURE = 'SET_ENGINE_OIL_TEMPERATURE';
export const SET_ENGINE_OIL_TEMPERATURE_SELECTED =
  'SET_ENGINE_OIL_TEMPERATURE_SELECTED';
export const SET_FUEL_INJECTION_TIMING = 'SET_FUEL_INJECTION_TIMING';
export const SET_FUEL_INJECTION_TIMING_SELECTED =
  'SET_FUEL_INJECTION_TIMING_SELECTED';
export const SET_ENGINE_FUEL_RATE = 'SET_ENGINE_FUEL_RATE';
export const SET_ENGINE_FUEL_RATE_SELECTED = 'SET_ENGINE_FUEL_RATE_SELECTED';
export const SET_DRIVERS_DEMAND_ENGINE_PERCENT_TORQUE =
  'SET_DRIVERS_DEMAND_ENGINE_PERCENT_TORQUE';
export const SET_DRIVERS_DEMAND_ENGINE_PERCENT_TORQUE_SELECTED =
  'SET_DRIVERS_DEMAND_ENGINE_PERCENT_TORQUE_SELECTED';
export const SET_ACTUAL_ENGINE_PERCENT_TORQUE =
  'SET_ACTUAL_ENGINE_PERCENT_TORQUE';
export const SET_ACTUAL_ENGINE_PERCENT_TORQUE_SELECTED =
  'SET_ACTUAL_ENGINE_PERCENT_TORQUE_SELECTED';
export const SET_ENGINE_REFERENCE_TORQUE = 'SET_ENGINE_REFERENCE_TORQUE';
export const SET_ENGINE_REFERENCE_TORQUE_SELECTED =
  'SET_ENGINE_REFERENCE_TORQUE_SELECTED';
export const SET_DPF_TEMPERATURE = 'SET_DPF_TEMPERATURE';
export const SET_DPF_TEMPERATURE_SELECTED = 'SET_DPF_TEMPERATURE_SELECTED';
export const SET_ENGINE_RUN_TIME = 'SET_ENGINE_RUN_TIME';
export const SET_ENGINE_RUN_TIME_SELECTED = 'SET_ENGINE_RUN_TIME_SELECTED';

export const SET_CODES_SHOWN = 'SET_CODES_SHOWN';
